// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhpjozajpnabvtomzpfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxocGpvemFqcG5hYnZ0b216cGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzM5OTgsImV4cCI6MjA3Mzc0OTk5OH0.BXY129PygAW16GD0lH6ak6a9SS36Cj3xPp4zXbi52Xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});